// AMBOSS-style term recognition: a curated list of medical terms to underline.
// Definitions are NOT hand-authored here (that doesn't scale to a 6-year curriculum) —
// they're fetched live, on hover, from established free medical reference sources
// (NIH MedlinePlus, falling back to Wikipedia) via /api/glossary.
export const MEDICAL_TERMS: string[] = [
  // Anatomy
  'peritoneum', 'peritoneal cavity', 'reflex arc', 'reflex action', 'spinal reflex',
  'monosynaptic reflex', 'polysynaptic reflex', 'stretch reflex', 'withdrawal reflex',
  'brachial plexus', 'lumbar plexus', 'sacral plexus', 'cervical plexus',
  'sciatic nerve', 'vagus nerve', 'phrenic nerve', 'median nerve', 'ulnar nerve',
  'radial nerve', 'femoral nerve', 'obturator nerve', 'facial nerve', 'trigeminal nerve',
  'olfactory nerve', 'optic nerve', 'cranial nerve', 'cranial nerves', 'peripheral nerve',
  'motor neuron', 'sensory neuron', 'afferent neuron', 'efferent neuron', 'interneuron',
  'synapse', 'neurotransmitter', 'acetylcholine', 'dopamine', 'serotonin', 'norepinephrine',
  'cerebellum', 'cerebrum', 'cerebral cortex', 'medulla oblongata', 'pons', 'thalamus',
  'hypothalamus', 'hippocampus', 'amygdala', 'corpus callosum', 'basal ganglia',
  'substantia nigra', 'meninges', 'cerebrospinal fluid', 'blood-brain barrier',
  'sarcomere', 'skeletal muscle', 'cardiac muscle', 'smooth muscle', 'myofibril',
  'neuromuscular junction', 'node of ranvier', 'myelin sheath', 'axon', 'dendrite',
  'epithelium', 'connective tissue', 'endothelium', 'mesothelium',
  // Physiology
  'action potential', 'resting membrane potential', 'depolarization', 'repolarization',
  'cardiac output', 'stroke volume', 'heart rate', 'ejection fraction', 'preload', 'afterload',
  'cardiac cycle', 'systole', 'diastole', 'blood pressure', 'mean arterial pressure',
  'glomerular filtration rate', 'renal blood flow', 'tubular reabsorption', 'tubular secretion',
  'renin-angiotensin system', 'aldosterone', 'antidiuretic hormone', 'vasopressin',
  'frank-starling mechanism', 'baroreceptor reflex', 'chemoreceptor',
  'oxygen-hemoglobin dissociation curve', 'gas exchange', 'tidal volume', 'vital capacity',
  'homeostasis', 'negative feedback', 'positive feedback', 'osmosis', 'diffusion',
  'active transport', 'membrane potential', 'second messenger',
  // Pathology
  'apoptosis', 'necrosis', 'metaplasia', 'dysplasia', 'hyperplasia', 'hypertrophy', 'atrophy',
  'atherosclerosis', 'thrombosis', 'embolism', 'infarction', 'ischemia', 'inflammation',
  'edema', 'fibrosis', 'granuloma', 'neoplasia', 'carcinoma', 'sarcoma', 'metastasis',
  // Cardiovascular
  'myocardial infarction', 'congestive heart failure', 'heart failure', 'atrial fibrillation',
  'arrhythmia', 'endocarditis', 'myocarditis', 'pericarditis', 'rheumatic fever',
  'deep vein thrombosis', 'pulmonary embolism', 'aneurysm', 'hypertension', 'hypotension',
  'shock', 'cardiomyopathy', 'valvular heart disease', 'coronary artery disease', 'angina',
  // Respiratory
  'pneumonia', 'tuberculosis', 'asthma', 'chronic obstructive pulmonary disease', 'bronchitis',
  'emphysema', 'pleural effusion', 'pneumothorax', 'respiratory failure', 'hypoxia',
  // GI
  'peptic ulcer disease', 'gastroesophageal reflux disease', 'cirrhosis', 'pancreatitis',
  'appendicitis', 'cholelithiasis', 'cholecystitis', "crohn's disease", 'ulcerative colitis',
  'celiac disease', 'diverticulitis', 'hepatitis', 'jaundice', 'portal hypertension',
  'irritable bowel syndrome', 'gastritis', 'malabsorption',
  // Renal
  'nephrotic syndrome', 'glomerulonephritis', 'urinary tract infection', 'renal failure',
  'acute kidney injury', 'chronic kidney disease', 'nephrolithiasis', 'pyelonephritis',
  // Endocrine
  'diabetes mellitus', 'diabetic ketoacidosis', 'hyperthyroidism', 'hypothyroidism',
  'cushing syndrome', "addison's disease", 'acromegaly', 'hyperglycemia', 'hypoglycemia',
  'goiter', 'thyroid storm', 'insulin resistance',
  // Hematology/Oncology
  'sickle cell anemia', 'hemophilia', 'leukemia', 'lymphoma', 'anemia', 'thrombocytopenia',
  'polycythemia', 'multiple myeloma', 'disseminated intravascular coagulation',
  // Neurology
  'multiple sclerosis', "parkinson's disease", "alzheimer's disease", 'epilepsy', 'meningitis',
  'stroke', 'seizure', 'migraine', 'encephalitis', 'neuropathy', 'guillain-barré syndrome',
  'myasthenia gravis',
  // Infectious
  'sepsis', 'malaria', 'hepatitis b virus', 'influenza', 'measles', 'tetanus', 'cellulitis',
  'abscess', 'bacteremia', 'septic shock',
  // Rheumatology / MSK
  'rheumatoid arthritis', 'osteoarthritis', 'systemic lupus erythematosus', 'gout',
  'osteoporosis', 'fracture', 'osteomyelitis',
  // Pharmacology
  'beta blocker', 'ace inhibitor', 'nsaid', 'corticosteroid', 'pharmacokinetics',
  'pharmacodynamics', 'half-life', 'agonist', 'antagonist', 'bioavailability',
  'calcium channel blocker', 'diuretic', 'loop diuretic', 'thiazide diuretic',
  'anticoagulant', 'antiplatelet', 'thrombolytic', 'antiarrhythmic', 'antihistamine',
  'antibiotic', 'antiviral', 'antifungal', 'antiparasitic', 'analgesic', 'opioid',
  'local anesthetic', 'general anesthetic', 'sedative', 'antidepressant', 'antipsychotic',
  'anxiolytic', 'anticonvulsant', 'bronchodilator', 'antiemetic', 'laxative',
  'proton pump inhibitor', 'h2 receptor antagonist', 'statin', 'insulin therapy',
  'vaccine', 'immunosuppressant', 'chemotherapy', 'first-pass metabolism', 'therapeutic index',
  // Histology
  'columnar epithelium', 'squamous epithelium', 'cuboidal epithelium', 'basement membrane',
  'goblet cell', 'ciliated epithelium', 'stratified epithelium', 'simple epithelium',
  'adipose tissue', 'areolar tissue', 'hyaline cartilage', 'elastic cartilage',
  'fibrocartilage', 'compact bone', 'spongy bone', 'osteon', 'osteocyte', 'osteoblast',
  'osteoclast', 'chondrocyte', 'fibroblast', 'macrophage', 'mast cell', 'plasma cell',
  'schwann cell', 'astrocyte', 'oligodendrocyte', 'microglia', 'purkinje cell',
  'langerhans cell', 'merkel cell', 'kupffer cell', 'mesangial cell', 'podocyte',
  'glomerulus', 'bowman\'s capsule', 'nephron', 'loop of henle', 'collecting duct',
  'alveolus', 'alveoli', 'bronchiole', 'villus', 'microvilli', 'crypts of lieberkühn',
  'islets of langerhans', 'hepatocyte', 'sinusoid', 'lobule', 'acinus',
  // Microbiology
  'gram-positive bacteria', 'gram-negative bacteria', 'bacteriophage', 'endotoxin',
  'exotoxin', 'biofilm', 'pathogen', 'commensal', 'staphylococcus aureus',
  'streptococcus pneumoniae', 'escherichia coli', 'mycobacterium tuberculosis',
  'helicobacter pylori', 'candida albicans', 'plasmodium falciparum', 'hiv',
  'sars-cov-2', 'herpes simplex virus', 'epstein-barr virus', 'cytomegalovirus',
  'antigen', 'antibody', 'innate immunity', 'adaptive immunity', 'complement system',
  'cytokine', 'interleukin', 'major histocompatibility complex', 'autoimmunity',
  'hypersensitivity reaction', 'vaccination', 'opsonization', 'phagocytosis',
  // Biochemistry
  'glycolysis', 'gluconeogenesis', 'krebs cycle', 'citric acid cycle', 'electron transport chain',
  'oxidative phosphorylation', 'beta oxidation', 'glycogenolysis', 'glycogenesis',
  'urea cycle', 'amino acid metabolism', 'lipid metabolism', 'enzyme kinetics',
  'competitive inhibition', 'allosteric regulation', 'atp synthase', 'mitochondria',
  'ribosome', 'endoplasmic reticulum', 'golgi apparatus', 'lysosome', 'peroxisome',
  'dna replication', 'transcription', 'translation', 'messenger rna', 'point mutation',
  'genetic mutation', 'codon', 'gene expression', 'chromosome', 'karyotype',
  // More diseases
  'down syndrome', 'turner syndrome', 'klinefelter syndrome', 'cystic fibrosis',
  'marfan syndrome', 'huntington disease', 'duchenne muscular dystrophy',
  'wilson disease', 'hemochromatosis', 'phenylketonuria', 'von willebrand disease',
  'graves disease', 'hashimoto thyroiditis', 'sjögren syndrome', 'scleroderma',
  'psoriasis', 'eczema', 'vitiligo', 'urticaria', 'anaphylaxis',
  'otitis media', 'sinusitis', 'pharyngitis', 'laryngitis', 'conjunctivitis',
  'glaucoma', 'cataract', 'retinal detachment', 'macular degeneration',
  'benign prostatic hyperplasia', 'prostate cancer', 'breast cancer', 'cervical cancer',
  'ovarian cancer', 'endometriosis', 'polycystic ovary syndrome', 'preeclampsia',
  'ectopic pregnancy', 'placenta previa', 'gestational diabetes',
  // Anatomy (more)
  'femur', 'tibia', 'fibula', 'humerus', 'radius', 'ulna', 'clavicle', 'scapula',
  'pelvis', 'sternum', 'vertebra', 'intervertebral disc', 'spinal cord', 'gray matter',
  'white matter', 'dura mater', 'arachnoid mater', 'pia mater', 'ventricle',
  'atrium', 'mitral valve', 'tricuspid valve', 'aortic valve', 'pulmonary valve',
  'coronary artery', 'aorta', 'vena cava', 'carotid artery', 'jugular vein',
  'portal vein', 'hepatic artery', 'renal artery', 'pulmonary artery', 'capillary',
  'lymph node', 'spleen', 'thymus', 'tonsil', 'bone marrow', 'trachea', 'larynx',
  'pharynx', 'epiglottis', 'diaphragm', 'pleura', 'esophagus', 'stomach', 'duodenum',
  'jejunum', 'ileum', 'cecum', 'colon', 'rectum', 'anal canal', 'liver', 'gallbladder',
  'pancreas', 'kidney', 'ureter', 'bladder', 'urethra', 'testis', 'epididymis',
  'vas deferens', 'prostate gland', 'ovary', 'fallopian tube', 'uterus', 'cervix',
  'vagina', 'placenta', 'umbilical cord', 'thyroid gland', 'parathyroid gland',
  'adrenal gland', 'pituitary gland', 'pineal gland', 'lacrimal gland', 'salivary gland',
  'parotid gland', 'retina', 'cornea', 'iris', 'lens', 'sclera', 'cochlea',
  'tympanic membrane', 'vestibular system', 'olfactory bulb', 'taste bud',
  // Pathology (more)
  'pyknosis', 'karyorrhexis', 'karyolysis', 'caseous necrosis', 'coagulative necrosis',
  'liquefactive necrosis', 'fat necrosis', 'gangrenous necrosis', 'fibrinoid necrosis',
  'dystrophic calcification', 'metastatic calcification', 'amyloidosis', 'hyalinization',
  'chronic inflammation', 'acute inflammation', 'exudate', 'transudate', 'pus',
  'abscess formation', 'organization', 'resolution', 'regeneration', 'scar formation',
  'keloid', 'leukoplakia', 'erythroplakia', 'hamartoma', 'teratoma', 'adenoma',
  'papilloma', 'lipoma', 'fibroma', 'hemangioma', 'angiosarcoma', 'osteosarcoma',
  'chondrosarcoma', 'liposarcoma', 'rhabdomyosarcoma', 'squamous cell carcinoma',
  'basal cell carcinoma', 'adenocarcinoma', 'transitional cell carcinoma',
  'tumor grading', 'tumor staging', 'tnm staging', 'paraneoplastic syndrome',
  'oncogene', 'tumor suppressor gene', 'angiogenesis', 'invasion',
  // Histology (more)
  'transitional epithelium', 'pseudostratified epithelium', 'desmosome', 'tight junction',
  'gap junction', 'hemidesmosome', 'reticular fiber', 'collagen fiber', 'elastic fiber',
  'tendon', 'ligament', 'periosteum', 'endosteum', 'haversian canal', 'lamellae',
  'lacuna', 'canaliculi', 'epiphyseal plate', 'growth plate', 'red bone marrow',
  'yellow bone marrow', 'spermatogenesis', 'oogenesis', 'corpus luteum', 'graafian follicle',
  'zona pellucida', 'sertoli cell', 'leydig cell', 'meissner corpuscle', 'pacinian corpuscle',
  'taste bud cell', 'olfactory receptor cell', 'rod cell', 'cone cell', 'photoreceptor',
  'pyramidal cell', 'glial cell', 'ependymal cell', 'satellite cell', 'pneumocyte',
  'type i pneumocyte', 'type ii pneumocyte', 'surfactant', 'parietal cell', 'chief cell',
  'g cell', 'paneth cell', 'enterochromaffin cell', 'brunner gland', 'crypt of lieberkühn',
  // Microbiology (more)
  'spore formation', 'bacterial capsule', 'flagella', 'pili', 'plasmid', 'transduction',
  'transformation', 'conjugation', 'antibiotic resistance', 'beta-lactamase',
  'neisseria gonorrhoeae', 'neisseria meningitidis', 'salmonella typhi', 'shigella',
  'vibrio cholerae', 'clostridium difficile', 'clostridium botulinum', 'clostridium perfringens',
  'listeria monocytogenes', 'haemophilus influenzae', 'klebsiella pneumoniae',
  'pseudomonas aeruginosa', 'treponema pallidum', 'chlamydia trachomatis',
  'mycoplasma pneumoniae', 'legionella pneumophila', 'bordetella pertussis',
  'corynebacterium diphtheriae', 'aspergillus', 'cryptococcus neoformans',
  'pneumocystis jirovecii', 'giardia lamblia', 'entamoeba histolytica',
  'toxoplasma gondii', 'trichomonas vaginalis', 'schistosoma', 'taenia solium',
  'hepatitis a virus', 'hepatitis c virus', 'varicella-zoster virus', 'rotavirus',
  'rabies virus', 'poliovirus', 'human papillomavirus', 'mumps virus', 'rubella virus',
  // Biochemistry (more)
  'cori cycle', 'pentose phosphate pathway', 'fatty acid synthesis', 'ketogenesis',
  'cholesterol synthesis', 'bile acid synthesis', 'heme synthesis', 'porphyria',
  'purine metabolism', 'pyrimidine metabolism', 'gout pathophysiology', 'lactate dehydrogenase',
  'creatine kinase', 'alanine aminotransferase', 'aspartate aminotransferase',
  'alkaline phosphatase', 'amylase', 'lipase', 'trypsin', 'pepsin', 'chymotrypsin',
  'hemoglobin structure', 'myoglobin', 'collagen synthesis', 'elastin', 'keratin',
  'actin', 'myosin', 'tropomyosin', 'troponin', 'cytoskeleton', 'microtubule',
  'microfilament', 'intermediate filament', 'cell cycle', 'mitosis', 'meiosis',
  'apoptosis pathway', 'cell signaling', 'g protein-coupled receptor', 'tyrosine kinase receptor',
  // Pharmacology (more)
  'penicillin', 'cephalosporin', 'macrolide', 'tetracycline', 'aminoglycoside',
  'fluoroquinolone', 'sulfonamide', 'vancomycin', 'metronidazole', 'rifampin',
  'isoniazid', 'ethambutol', 'pyrazinamide', 'acyclovir', 'oseltamivir',
  'fluconazole', 'amphotericin b', 'warfarin', 'heparin', 'aspirin', 'clopidogrel',
  'metformin', 'sulfonylurea', 'thiazolidinedione', 'glp-1 agonist', 'sglt2 inhibitor',
  'levothyroxine', 'methimazole', 'propylthiouracil', 'prednisone', 'hydrocortisone',
  'morphine', 'fentanyl', 'tramadol', 'acetaminophen', 'ibuprofen', 'diclofenac',
  'lidocaine', 'bupivacaine', 'propofol', 'ketamine', 'midazolam', 'diazepam',
  'phenytoin', 'carbamazepine', 'valproate', 'lamotrigine', 'levetiracetam',
  'fluoxetine', 'sertraline', 'haloperidol', 'risperidone', 'lithium',
  'albuterol', 'salmeterol', 'ipratropium', 'theophylline', 'montelukast',
  'omeprazole', 'ranitidine', 'metoclopramide', 'ondansetron', 'loperamide',
  'furosemide', 'spironolactone', 'hydrochlorothiazide', 'amlodipine', 'metoprolol',
  'atenolol', 'propranolol', 'lisinopril', 'losartan', 'atorvastatin', 'digoxin',
  // Common clinical abbreviations (standard, widely-used shorthand — not a
  // reproduction of any single proprietary glossary/dataset)
  'chf', 'copd', 'ckd', 'aki', 'uti', 'dvt', 'gerd', 'ibd', 'ibs',
  'sle', 'dka', 'cva', 'tia', 'als', 'gbs', 'cad', 'htn', 'afib', 'cabg', 'pci',
  'cxr', 'ecg', 'ekg', 'cbc', 'bmp', 'cmp', 'abg', 'lft', 'ptt', 'inr', 'esr',
  'crp', 'bun', 'gfr', 'hba1c', 'ldl', 'hdl', 'tsh', 'fsh', 'acth', 'adh', 'pth',
  'hcg', 'psa', 'ana', 'rbc', 'wbc', 'hgb', 'hct', 'plt', 'ssri', 'snri', 'ppi',
  'cns', 'msk', 'rom', 'dnr', 'icu',
  // AMA Glossary of Medical Terms — headwords only (sourced from www.ama-assn.org
  // via a user-provided PDF; definitions intentionally excluded, as those remain
  // the AMA's copyrighted compiled content)
  'abdominal cavity', 'abo blood groups', 'abortion', 'achilles tendon', 'acid reflux',
  'acid-base balance', 'acidosis', 'acne', 'acquired immunodeficiency syndrome',
  'acute respiratory disease', 'addiction', 'adenitis', 'adjuvant therapy', 'adrenal failure',
  'adrenal glands', 'adverse reaction', 'aerobic exercise', 'affective disorder', 'afterbirth',
  'afterpains', 'aids', 'aids-related complex', 'air embolism', 'airway obstruction',
  'airways', 'albinism', 'alcoholic cardiomyopathy', 'alimentary canal', 'alkalosis',
  'alkylating agents', 'allergen', 'allergic rhinitis', 'allergy', 'alopecia', 'als',
  'altitude sickness', 'alzheimer disease', 'amenorrhea', 'amniocentesis', 'amniotic fluid',
  'amyotrophic lateral sclerosis', 'anabolic steroid', 'anal fissure', 'anal fistula',
  'anal sphincter', 'anaphylactic shock', 'anatomy', 'androgen', 'anencephaly', 'anesthesia',
  'anesthetic', 'angina pectoris', 'angioma', 'angioplasty', 'anorexia nervosa', 'antacid',
  'antibiotic resistance', 'antibiotics', 'antibody', 'anticoagulants', 'antiemetics',
  'antihypertensives', 'antioxidants', 'antipsychotics', 'antiseptics', 'anus', 'aorta',
  'aortic stenosis', 'apgar score', 'aplasia', 'aplastic anemia', 'apnea', 'appendectomy',
  'appendix', 'arteriosclerosis', 'arteritis', 'artery', 'arthritis', 'arthroscopy',
  'artificial insemination', 'artificial respiration/ventilation', 'ascites', 'ascorbic acid',
  'aspermia', 'asphyxia', 'astigmatism', 'atherectomy', 'atheroma', 'athlete\'s foot',
  'atresia', 'atria', 'atrial flutter', 'atrial septal defect', 'attention-deficit disorder',
  'audiogram', 'aura', 'auscultation', 'autism', 'autoimmune disease',
  'autonomic nervous system', 'autopsy', 'autosomal dominant', 'autosomal recessive', 'axilla',
  'b cell', 'b lymphocyte', 'bacillus', 'bacteriostatic', 'bacterium', 'bacteriuria',
  'ball-and-socket joint', 'balloon angioplasty', 'balloon catheter', 'barbiturates',
  'barium enema', 'barrier method of contraception', 'bartholin\'s glands',
  'basal cell carcinoma', 'basal metabolic rate', 'bcg vaccine', 'bell\'s palsy',
  'benign tumor', 'beta carotene', 'bifocal', 'bilateral', 'bile', 'bile duct',
  'biliary atresia', 'biliary colic', 'biliary tract', 'bilirubin', 'binging and purging',
  'biochemistry', 'bioequivalent', 'biofeedback', 'bipolar disorder', 'birth canal',
  'birth control', 'birth defect', 'birthmark', 'bisexuality', 'bladder', 'blepharitis',
  'blind spot', 'blood clot', 'blood poisoning', 'blood transfusion', 'blood type', 'boil',
  'bone marrow', 'bone marrow transplant', 'bone spur', 'booster', 'botulism', 'bowel',
  'bradycardia', 'brain damage', 'brain death', 'breech birth', 'bronchiolitis',
  'bronchoconstrictor', 'bronchospasm', 'bruise', 'bruxism', 'bubonic plague', 'bulimia',
  'bunion', 'burkitt\'s lymphoma', 'bursa', 'bursitis', 'butterfly bandage', 'bypass',
  'calcification', 'calcitonin', 'calcium', 'callus', 'calorie', 'canal', 'cancer',
  'cancer staging', 'candidiasis', 'canker sore', 'capillary', 'carbohydrate',
  'carbon dioxide', 'carcinogen', 'cardiac arrest', 'cardiogenic shock', 'cardiomegaly',
  'cardiopulmonary resuscitation', 'cardiovascular system', 'carditis', 'carotene',
  'carotid arteries', 'carpal bones', 'carpal tunnel syndrome', 'cartilage', 'cat scanning',
  'cat-scratch fever', 'cataract', 'catheter', 'catheterization', 'cauliflower ear',
  'cauterization', 'cecum', 'central nervous system', 'cerebral palsy',
  'cerebrovascular disease', 'cervical cap', 'cervical dysplasia', 'cervical incompetence',
  'cervical smear', 'cervicitis', 'cervix', 'cesarean section', 'chancre', 'chickenpox',
  'chlamydia', 'cholecystectomy', 'cholera', 'cholesterol', 'chondritis', 'chondroma',
  'chondromalacia patellae', 'chondrosarcoma', 'chorionic villus sampling', 'choroiditis',
  'chromosome analysis', 'chronic obstructive lung disease', 'cilia', 'circumcision',
  'cirrhosis of the liver', 'claudication', 'claustrophobia', 'clavicle', 'cleft lip',
  'cleft palate', 'clinical trial', 'clitoris', 'clone', 'closed fracture', 'clotting factor',
  'clubfoot', 'cluster headache', 'cns', 'coagulation', 'cocarcinogen', 'coccyx', 'cochlea',
  'coitus', 'cold sore', 'colectomy', 'colitis', 'collapsed lung', 'colon', 'colonoscopy',
  'color blindness', 'colostomy', 'coma', 'comminuted fracture', 'common cold',
  'communicable disease', 'compound fracture', 'compression fracture',
  'computed tomography scanning', 'concussion', 'conjunctiva', 'conjunctivitis',
  'constipation', 'contraindication', 'contusion', 'cornea', 'coronary', 'coronary arteries',
  'coronary artery bypass surgery', 'coronary heart disease', 'coronary thrombosis',
  'corpuscle', 'corticosteroids', 'cpr', 'creatinine', 'croup', 'cruciate ligaments',
  'ct scanning', 'culture', 'curettage', 'cvs', 'cyanosis', 'cyst', 'cystectomy',
  'cystic fibrosis', 'cystoscopy', 'cystostomy', 'd and c', 'debridement',
  'decompression sickness', 'deep-vein thrombosis', 'defecation', 'defibrillation',
  'degenerative arthritis', 'dehydration', 'dementia', 'depilatory', 'depot injection',
  'depression', 'dermabrasion', 'dermatitis', 'dermis', 'desensitization', 'detoxification',
  'dextrocardia', 'dextrose', 'diabetes insipidus', 'diabetes mellitus', 'dialysis',
  'diaper rash', 'diaphragm', 'diastolic pressure', 'diathermy', 'dilatation and curettage',
  'diphtheria', 'disk prolapse', 'dislocation', 'distention', 'diverticulitis', 'dna',
  'dominant gene', 'down syndrome', 'duchenne muscular dystrophy', 'duodenal ulcer',
  'duodenum', 'dysentery', 'dyspnea', 'dystrophy', 'eardrum', 'ecg (sometimes called an ekg)',
  'echocardiogram', 'eclampsia', 'ectopic', 'eczema', 'eeg', 'elective',
  'electroencephalography', 'embryo', 'emetic', 'endarterectomy', 'endemic', 'endocardium',
  'endocrine gland', 'endogenous', 'endometrial polyp', 'endometriosis', 'endometrium',
  'endophthalmitis', 'endorphin', 'endoscope', 'endotracheal tube', 'enteritis',
  'enterobiasis', 'enuresis', 'enzyme', 'epidemic', 'epidermis', 'epididymis',
  'epidural anesthesia', 'epinephrine', 'episcleritis', 'episiotomy', 'epstein-barr virus',
  'erysipelas', 'erythema', 'erythrocyte', 'erythrocyte sedimentation rate', 'erythroplakia',
  'esophageal spasm', 'esophageal varices', 'esophagus', 'estrogen',
  'estrogen replacement therapy', 'eustachian tube', 'euthanasia', 'excision', 'excretion',
  'exercise stress test', 'exercise thallium test', 'exogenous', 'expectorant',
  'extensor muscle', 'external version', 'extracorporeal shock wave lithotripsy',
  'extradural anesthesia', 'facial palsy', 'failure to thrive', 'fallopian tube', 'familial',
  'fasciitis', 'fatty acid', 'febrile', 'fecal occult blood test', 'femoral artery', 'femur',
  'fertility', 'fertility drug', 'fertilization', 'fetal alcohol syndrome', 'fetal distress',
  'fetal monitoring', 'fetal tissue transplant', 'fetus', 'fiber', 'fiberoptics',
  'fibrillation', 'fibroadenoma', 'fibrocystic breast disease', 'fibroid', 'fibroma',
  'fifth disease', 'fissure', 'fistula', 'fitness', 'flatulence', 'floaters', 'flu', 'fluke',
  'fluoride', 'fluoroscopy', 'folic acid', 'follicle', 'follicle stimulating hormone',
  'folliculitis', 'fontanelles', 'food poisoning', 'forceps', 'forceps delivery',
  'foreign body', 'foreskin', 'fraternal twins', 'free radical', 'frostbite', 'fsh',
  'fulminant', 'fungus', 'galactocele', 'galactorrhea', 'galactose', 'galactosemia',
  'gallbladder', 'gallstone', 'gallstone ileus', 'gamete intrafallopian transfer',
  'gamma globulin', 'ganglion', 'gangrene', 'gastrectomy', 'gastric acid', 'gastric juice',
  'gastric lavage', 'gastric ulcer', 'gastrin', 'gastrinoma', 'gastritis', 'gastroenteritis',
  'gastrointestinal series', 'gastrointestinal tract', 'gastroscopy', 'gastrostomy', 'gavage',
  'gene', 'gene therapy', 'general anesthesia', 'generic drug', 'genetic analysis',
  'genetic counseling', 'genetic disorder', 'genetic engineering', 'genital herpes',
  'genital tract', 'genital wart', 'genome', 'geographic tongue', 'germ cell',
  'german measles', 'gestation', 'gi series', 'giardiasis', 'gingivectomy', 'gingivitis',
  'gland', 'glaucoma', 'glioblastoma multiforme', 'glioma', 'glomerulonephritis',
  'glomerulosclerosis', 'glossectomy', 'glucagon', 'glucose', 'glucose tolerance test',
  'glycogen', 'glycosuria', 'gonadotropic hormones', 'gonorrhea', 'graft', 'grand mal',
  'graves\' disease', 'guthrie test', 'h1 (histamine) blocker', 'h2 (histamine) blocker',
  'hair follicle', 'halitosis', 'hallucination', 'hammer toe', 'hamstring muscle',
  'hardening of the arteries', 'hay fever', 'hdl', 'heart attack', 'heart block',
  'heart disease', 'heart valve', 'heart-lung machine', 'heartburn', 'heat exhaustion',
  'heat stroke', 'heel spur', 'heimlich maneuver', 'helper t cells', 'hemangioma',
  'hemarthrosis', 'hematemesis', 'hematocrit', 'hematoma', 'hematuria', 'hemochromatosis',
  'hemodialysis', 'hemoglobin', 'hemoglobinuria', 'hemolysis', 'hemorrhage', 'hemorrhoid',
  'hemospermia', 'hemostasis', 'hemothorax', 'hepatectomy', 'hepatic', 'hepatitis',
  'hepatitis a', 'hepatitis b', 'hepatitis c', 'hepatitis d', 'hepatoma', 'hepatomegaly',
  'hereditary', 'hereditary spherocytosis', 'hermaphroditism', 'hernia', 'herniated disk',
  'herpes encephalitis', 'herpes simplex', 'herpes zoster', 'heterosexuality', 'hiatal hernia',
  'hiccup', 'high-density lipoprotein', 'hirschsprung\'s disease', 'hirsutism', 'histamine',
  'histoplasmosis', 'hiv', 'hives', 'hodgkin\'s disease', 'homocystinuria', 'homosexuality',
  'hookworm', 'hormonal implant', 'hormone', 'hormone replacement therapy', 'hospice',
  'hot flash', 'htlv', 'human immunodeficiency virus', 'human t-cell lymphotrophic virus',
  'hydramnios', 'hydrocele', 'hydrocephalus', 'hydrocortisone', 'hygiene', 'hymen',
  'hyperactivity', 'hyperalimentation', 'hyperbilirubinemia', 'hypercalcemia',
  'hypercholesterolemia', 'hyperlipidemia', 'hyperparathyroidism', 'hypersensitivity',
  'hyperthermia', 'hyperthyroidism', 'hyperventilation', 'hypochondriasis',
  'hypodermic needle', 'hypoplasia', 'hypothermia', 'hypothyroidism', 'hypoventilation',
  'hypoxemia', 'hysterectomy', 'hysteria', 'hysterosalpingography', 'hysteroscopy',
  'iatrogenic', 'ichthyosis', 'idiopathic', 'ileostomy', 'ileum', 'ilium', 'immune deficiency',
  'immune system', 'immunization', 'immunocompromised', 'immunodeficiency', 'immunoglobin',
  'immunology', 'immunostimulant', 'impacted fracture', 'imperforate anus', 'impetigo',
  'implant', 'impotence', 'in situ', 'in vitro', 'in vitro fertilization', 'in vivo',
  'incompetent cervix', 'incontinence', 'incubation period', 'indigestion',
  'induction of labor', 'infective arthritis', 'infertility', 'inflammatory bowel disease',
  'inflammatory joint disease', 'informed consent', 'infusion', 'ingestion', 'ingrown toenail',
  'inguinal hernia', 'inhaler', 'inheritance', 'injection', 'insemination', 'insomnia',
  'insulin', 'insulinoma', 'intensive care', 'interferon', 'internal fixation', 'interstitial',
  'interstitial cystitis', 'interstitial lung disease', 'interstitial pulmonary fibrosis',
  'interstitial radiation therapy', 'intervertebral disks', 'intestinal bypass', 'intestine',
  'intra-aortic balloon pump', 'intractable', 'intramedullary rod', 'intraocular pressure',
  'intrauterine device', 'intravenous', 'intrinsic', 'intubation', 'invasive', 'involuntary',
  'iodine', 'ionizing radiation', 'iris', 'iron', 'iron-deficiency anemia', 'irrigation',
  'irritable bladder', 'irritable bowel syndrome', 'iud', 'ivf', 'jaundice', 'jock itch',
  'juvenile rheumatoid arthritis', 'kaposi\'s sarcoma', 'kawasaki disease', 'keloid',
  'keratin', 'keratitis', 'keratolytic', 'keratoplasty', 'keratosis', 'ketoacidosis', 'kidney',
  'kidney stone', 'killer t cells', 'kilocalorie', 'kimmelstiel-wilson syndrome',
  'knee-jerk reflex', 'kyphosis', 'labia', 'labor', 'labyrinthitis', 'laceration',
  'lactase deficiency', 'lactation', 'lactation suppression', 'lactic acid', 'lactose',
  'lactose intolerance', 'lamaze method', 'laminectomy', 'laparoscope',
  'laparoscopic cholecystectomy', 'laparoscopy', 'large intestine', 'large-cell carcinoma',
  'laryngectomy', 'laryngitis', 'larynx', 'laser treatment', 'latent infection', 'lateral',
  'laxatives', 'lazy eye', 'ldl', 'lead poisoning', 'learning disability', 'leiomyoma',
  'leishmaniasis', 'leptospirosis', 'lesch-nyhan syndrome', 'leukocyte', 'leukocyte count',
  'leukodystrophy', 'leukoplakia', 'lichen planus', 'ligament', 'ligation',
  'lipid-lowering drugs', 'lipidosis', 'lipids', 'lipoma', 'lipoproteins', 'liposarcoma',
  'liposuction', 'listeriosis', 'lithotripsy', 'liver', 'liver failure', 'lobe', 'lobectomy',
  'local anesthesia', 'locked joint', 'lockjaw', 'locomotor system', 'lordosis',
  'lou gehrig\'s disease', 'low-density lipoprotein', 'lumbago', 'lumbar puncture',
  'lumbar spine', 'lumpectomy', 'lung collapse', 'lungs', 'lupus erythematosus',
  'luteinizing hormone', 'lyme disease', 'lymph', 'lymph node', 'lymphadenopathy',
  'lymphangiography', 'lymphatic system', 'lymphocyte', 'lymphocytic leukemia',
  'lymphogranuloma venereum', 'lymphomas', 'lymphosarcoma', 'macula', 'macular degeneration',
  'magnesium', 'magnetic resonance imaging (mri)', 'malabsorption', 'malformation',
  'malignant hyperthermia', 'malignant melanoma', 'mallory-weiss syndrome', 'mammography',
  'mammoplasty', 'mandible', 'mania', 'manic-depressive disorder', 'mao inhibitor',
  'marfan\'s syndrome', 'mastectomy', 'mastitis', 'maxilla', 'meconium', 'mediastinoscopy',
  'medulla', 'medulloblastoma', 'megacolon', 'megaloblastic anemia', 'meiosis', 'melanin',
  'melanocyte-stimulating hormone', 'melanocytes', 'melanoma', 'menarche',
  'meniere\'s disease', 'meningioma', 'meningocele', 'meniscectomy', 'meniscus', 'menopause',
  'menorrhagia', 'menstrual cycle', 'menstruation', 'mesenteric infarction',
  'mesenteric lymphadenitis', 'mesothelioma', 'messenger rna', 'metabolic rate', 'metabolism',
  'metabolite', 'metered-dose inhaler', 'microbe', 'microbiology', 'microcephaly',
  'microdiskectomy', 'microorganism', 'microsurgery', 'micturition syncope', 'middle ear',
  'middle ear effusion', 'midwifery', 'mineral', 'minipill', 'miotic', 'miscarriage', 'mites',
  'mitosis', 'mitral insufficiency', 'mitral stenosis', 'mitral valve',
  'mitral valve prolapse', 'modified radical mastectomy', 'molar tooth', 'molecule',
  'molluscum contagiosum', 'mongolian spot', 'monoamine oxidase inhibitor antidepressant',
  'monoclonal antibodies', 'mononucleosis', 'monounsaturated fat', 'morbidity',
  'morning sickness', 'mortality', 'motor nerve', 'motor neuron disease',
  'mouth-to-mouth resuscitation', 'mri', 'mucocele', 'mucolytic', 'mucous membrane', 'mucus',
  'multi-infarct dementia', 'multiple pregnancy', 'multiple-gated acquisition scan', 'mumps',
  'murmur', 'muscle fibers', 'muscle relaxants', 'muscle tone', 'muscle wasting',
  'muscular dystrophy', 'mutagen', 'mutation', 'myalgia', 'mycobacterium', 'mycoplasma',
  'mycosis', 'mydriatic', 'myelitis', 'myelocele', 'myeloma', 'myelosclerosis', 'myocardium',
  'myomectomy', 'myopathy', 'myopia', 'myositis', 'myringotomy', 'myxoma', 'narcolepsy',
  'narcosis', 'narcotic', 'narcotic analgesics', 'nasal septum', 'nasogastric tube',
  'nasopharynx', 'natural childbirth', 'natural methods of family planning', 'nausea',
  'nebulizer', 'needle aspiration', 'needle biopsy', 'neonate', 'neoplasm', 'nephrectomy',
  'nephritis', 'nephroblastoma', 'nephrolithotomy', 'nephrons', 'nephrosclerosis',
  'nephrostomy', 'nephrotic syndrome', 'nerve', 'nerve block', 'nerve cell',
  'nerve compression', 'neural tube', 'neural tube defects', 'neuralgia', 'neuritis',
  'neuroblastoma', 'neurofibrillary tangles', 'neurofibromatosis', 'neuroleptic', 'neuroma',
  'neuron', 'neurosis', 'neurotoxins', 'neurotransmitters', 'neutrophil', 'nevus',
  'newborn respiratory distress syndrome', 'niacin', 'night terrors', 'nitrates', 'nocturia',
  'nocturnal emission', 'nodule', 'non-hodgkin\'s lymphoma', 'non-insulin-dependent diabetes',
  'nondisjunction', 'noninvasive', 'nonnarcotic analgesic',
  'nonsteroidal anti-inflammatory drugs', 'norwalk virus', 'nosocomial infection',
  'nucleic acids', 'nucleotide bases', 'nucleus', 'numbness', 'nurse-midwife', 'nutrient',
  'nystagmus', 'oat cell carcinoma', 'obesity', 'obsessive-compulsive disorder',
  'obstructive sleep apnea', 'occlusion', 'occult blood', 'occupational disease',
  'occupational therapy', 'ocular', 'oculomotor nerves', 'olfactory nerves',
  'oligodendroglioma', 'oligohydramnios', 'oligospermia', 'oncogenes', 'oocyte',
  'oophorectomy', 'open heart surgery', 'ophthalmia', 'ophthalmologist', 'ophthalmoplegia',
  'ophthalmoscopy', 'opportunistic infection', 'optic', 'optic nerves', 'optic neuritis',
  'optician', 'oral contraceptives', 'orbit', 'orchiectomy', 'orchiopexy', 'orchitis',
  'organ donation', 'organism', 'orgasm', 'orphan drugs', 'orthopnea', 'orthotic',
  'osgood-schlatter disease', 'ossification', 'osteitis', 'osteitis deformans',
  'osteochondritis dissecans', 'osteochondritis juvenilis', 'osteochondroma', 'osteodystrophy',
  'osteogenesis imperfecta', 'osteolysis', 'osteoma', 'osteomalacia', 'osteopetrosis',
  'osteophyte', 'osteosarcoma', 'osteosclerosis', 'otalgia', 'otc remedy', 'otitis externa',
  'otitis media', 'otorrhea', 'otosclerosis', 'ototoxicity', 'outpatient treatment', 'ovaries',
  'over-the-counter remedy', 'overdose', 'ovulation', 'ovum', 'oxidation', 'oximetry',
  'oxygen', 'oxygen free radicals', 'oxytocin', 'ozone', 'pacemaker', 'paget\'s disease',
  'palate', 'palliative treatment', 'pallor', 'palpation', 'palpitation', 'palsy', 'pancreas',
  'pandemic', 'panic disorder', 'pap smear', 'papilloma', 'paracentesis', 'paralysis',
  'paramedic', 'paranoia', 'paraphimosis', 'paraplegia', 'parasite',
  'parasympathetic nervous system', 'parathyroid glands', 'parathyroid hormone',
  'parathyroidectomy', 'parenteral', 'paresis', 'paresthesia', 'parkinson\'s disease',
  'paronychia', 'parotid glands', 'paroxysm', 'partial mastectomy', 'partial seizure',
  'passive exercise', 'passive smoking', 'patella', 'patent ductus arteriosus',
  'paternity testing', 'pathogen', 'pathogenesis', 'pathology', 'patient-controlled analgesia',
  'peak flow measurement', 'pectoral muscles', 'pellagra', 'pelvic examination',
  'pelvic inflammatory disease', 'pelvis', 'penile function tests', 'penile implant', 'penis',
  'pepsin', 'peptic ulcer', 'percutaneous', 'perforation', 'periarteritis nodosa',
  'pericardial effusion', 'pericardium', 'perinatal', 'periosteum', 'periostitis',
  'peripheral nervous system', 'peripheral vascular disease', 'peristalsis', 'peritonitis',
  'pernicious anemia', 'perthes\' disease', 'pertussis', 'pet scanning', 'petit mal',
  'peutz-jeghers syndrome', 'phagocyte', 'phantom limb', 'pharmacology', 'pharyngitis',
  'pharynx', 'phenothiazines', 'phenylketonuria', 'pheochromocytoma', 'phimosis', 'phlebitis',
  'phlebothrombosis', 'phlegm', 'phobia', 'phosphates', 'phospholipids', 'phosphorus',
  'photocoagulation', 'photophobia', 'photosensitivity', 'phototherapy', 'physical therapy',
  'physiology', 'phytochemicals', 'pica', 'pickwickian syndrome', 'pid', 'pigmentation',
  'pinkeye', 'pinworm', 'pituitary adenoma', 'pituitary gland', 'pityriasis alba',
  'pityriasis rosea', 'pivot joint', 'pku', 'placebo', 'placebo effect', 'placenta',
  'placenta previa', 'placental abruption', 'placental insufficiency', 'plantar reflex',
  'plantar wart', 'plaque', 'plasma', 'plasmapheresis', 'platelet', 'pleura',
  'pleural membranes', 'pleural rub', 'pleural space', 'pleurisy', 'pleurodynia',
  'plummer-vinson syndrome', 'pms', 'pneumoconiosis', 'pneumocystis pneumonia',
  'pneumonectomy', 'poliomyelitis', 'polyarthritis', 'polycystic kidney disease',
  'polycystic ovary syndrome', 'polydactyly', 'polydipsia', 'polymyalgia rheumatica',
  'polymyositis', 'polyp', 'polysaccharide', 'polyunsaturated fat', 'polyuria', 'porphyria',
  'portal hypertension', 'portal vein', 'positron emission tomography scanning',
  'post-traumatic stress disorder', 'postcoital contraception', 'posterior',
  'postmenopausal bleeding', 'postmortem examination', 'postmyocardial infarction syndrome',
  'postnatal', 'postpartum', 'postural drainage', 'postural hypotension', 'potassium',
  'precancerous', 'precordial movement', 'preeclampsia', 'premature labor',
  'premature rupture of membranes', 'premedication', 'premenopausal', 'premenstrual syndrome',
  'prenatal care', 'prenatal diagnosis', 'prenatal testing', 'prepared childbirth', 'prepuce',
  'presbycusis', 'presbyopia', 'pressure point', 'pressure sore', 'priapism', 'prickly heat',
  'primary', 'prion', 'procidentia', 'proctalgia', 'proctitis', 'proctoscopy',
  'productive cough', 'progeria', 'progesterone', 'prognosis', 'progressive muscular atrophy',
  'prolactin', 'prolapse', 'prolapsed disk', 'prophylactic', 'proprioception',
  'prostate gland', 'prostatectomy', 'prostatism', 'prostatitis', 'prosthesis', 'proteins',
  'prothrombin time', 'proto-oncogene', 'protozoan', 'proximal', 'pruritus', 'pseudogout',
  'pseudomembranous enterocolitis', 'psittacosis', 'psoralens', 'psoriasis',
  'psoriatic arthritis', 'psychogenic', 'psychological', 'psychosis', 'psychosomatic',
  'psychotherapy', 'psychotic', 'psychotropic drug', 'ptosis', 'puberty', 'pubic louse',
  'pudendal block', 'pudendum', 'puerperal sepsis', 'puerperium', 'pulmonary artery',
  'pulmonary edema', 'pulmonary fibrosis', 'pulmonary heart valve', 'pulmonary hypertension',
  'pulmonary insufficiency', 'pulmonary stenosis', 'pulse', 'pupil', 'purpuric rash', 'pus',
  'pustule', 'puva', 'pyelolithotomy', 'pyelonephritis', 'pyloric sphincter',
  'pyloric stenosis', 'pyloroplasty', 'pyrexia', 'pyrogen', 'pyuria', 'quadriceps muscle',
  'rabies', 'radial keratotomy', 'radiation', 'radiation therapy', 'radical surgery',
  'radiculopathy', 'radioallergosorbent test', 'radiography', 'radionuclide scanning',
  'radius', 'radon', 'rales', 'rash', 'raynaud\'s disease', 'receptor', 'recessive gene',
  'reconstructive surgery', 'rectal prolapse', 'rectum', 'red blood cell',
  'reduction of fracture', 'referred pain', 'reflux esophagitis', 'regurgitation',
  'rehabilitation', 'rehydration', 'reiter\'s syndrome', 'rem sleep', 'renal cell carcinoma',
  'renal colic', 'renal tubular acidosis', 'renin', 'repetitive strain injury',
  'reproductive system', 'resection', 'respiration', 'respirator', 'respiratory arrest',
  'respiratory distress syndrome', 'respiratory system', 'resting pulse', 'reticulocyte',
  'retina', 'retinal artery occlusion', 'retinitis pigmentosa', 'retinoblastoma', 'retinoid',
  'retinopathy', 'retinoscopy', 'retroviruses', 'reye\'s syndrome', 'rh blood group',
  'rh immunoglobulin', 'rh incompatibility', 'rh sensitized', 'rheumatoid factors', 'rhinitis',
  'rhinophyma', 'rhinoplasty', 'rhythm method', 'riboflavin', 'rickets', 'rigor mortis',
  'ringworm', 'rinne\'s test', 'rna', 'rocky mountain spotted fever', 'rosacea',
  'roseola infantum', 'rotator cuff', 'roundworm', 'rubella', 'rubeola', 'rupture',
  'saccharides', 'sacroiliac joints', 'sacroiliitis', 'sacrum', 'sads', 'safe sex', 'saline',
  'salivary glands', 'salmonella', 'salmonellosis', 'salpingectomy', 'salpingitis',
  'salpingo-oophorectomy', 'salpingography', 'salpingolysis', 'salpingostomy', 'sarcoidosis',
  'saturated fat', 'saturday night palsy', 'scabies', 'scarlet fever', 'schistosomiasis',
  'schizophrenia', 'sciatica', 'sclera', 'scleroderma', 'sclerotherapy', 'scoliosis',
  'scrotum', 'scurvy', 'seasonal affective disorder syndrome', 'sebaceous cyst', 'seborrhea',
  'sebum', 'secondary', 'sedatives', 'selenium', 'semen', 'semen analysis', 'seminal vesicles',
  'seminiferous tubules', 'seminoma', 'senile plaques', 'sensorineural hearing loss',
  'sensory nerve', 'sensory organ', 'septal defect', 'septic arthritis', 'septicemia', 'serum',
  'sex chromosomes', 'sex hormones', 'sex-linked disorder', 'sexually transmitted disease',
  'shigellosis', 'shin splints', 'shingles', 'shunt', 'sick sinus syndrome',
  'sickle cell trait', 'sids', 'sigmoidoscopy', 'silicone', 'silicosis',
  'single photon emission computed tomography', 'sinoatrial node', 'sinus',
  'sinus bradycardia', 'sinus rhythm', 'sinus tachycardia', 'sinusitis', 'skin graft',
  'skin patch', 'skin patch test', 'skin prick test', 'skull', 'sleep apnea',
  'sleeping sickness', 'slipped disk', 'small intestine', 'small-cell carcinoma', 'smallpox',
  'sodium', 'sodium bicarbonate', 'solar plexus', 'somatic', 'spastic paralysis', 'spasticity',
  'spect', 'speculum', 'speech therapy', 'sperm', 'sperm antibody', 'sperm count',
  'spermatocele', 'spermicide', 'sphincter', 'sphygmomanometer', 'spider nevus',
  'spina bifida', 'spina bifida occulta', 'spinal cord', 'spinal fusion', 'spinal tap',
  'spine', 'spiral fracture', 'spirometry', 'spleen', 'splenectomy', 'splint',
  'splinter hemorrhage', 'spondylitis', 'spondylolisthesis', 'spondylolysis', 'sporotrichosis',
  'sprain', 'sprue', 'sputum', 'squamous cell carcinoma', 'stapedectomy', 'staphylococci',
  'status asthmaticus', 'status epilepticus', 'std', 'stein-leventhal syndrome', 'stem cells',
  'stenosis', 'stent', 'stereotaxic surgery', 'sterilization', 'sternum', 'steroids',
  'stillbirth', 'stoma', 'stomach bypass', 'stomach stapling', 'stool', 'strabismus',
  'straight-leg raising', 'strangulated hernia', 'strawberry nevus', 'strep throat',
  'streptococci', 'stress fracture', 'stretch marks', 'stye', 'subcutaneous', 'submucosa',
  'suction lipectomy', 'sudden infant death syndrome', 'suppository', 'suppuration',
  'surfactant', 'surrogate', 'suture', 'sweat glands', 'sweat test', 'swimmer\'s ear',
  'sycosis barbae', 'sympathetic nervous system', 'syndactyly', 'synovectomy',
  'synovial fluid', 'synovial membrane', 'synovitus', 'syphilis', 'systemic',
  'systemic inflammatory response syndrome', 'systolic pressure', 't cell', 't-cell leukemia',
  't-lymphocyte', 't-lymphocyte killer cell', 'tachycardia', 'tapeworm', 'tarsorrhaphy',
  'tartar', 'tay-sachs disease', 'tear duct', 'telangiectasia', 'temperature method',
  'temporal arteritis', 'temporomandibular joint syndrome', 'tendinitis', 'tendon',
  'tendon transfer', 'tennis elbow', 'tenosynovitis', 'tenovaginitis', 'tens',
  'tension headache', 'teratogen', 'teratoma', 'termination of pregnancy', 'testicles',
  'testicular feminization factor', 'testicular torsion', 'testosterone', 'tetracyclines',
  'tetralogy of fallot', 'thalassemia', 'thallium scanning', 'therapeutic range',
  'thoracoscopy', 'thoracotomy', 'thorax', 'thrill', 'thrombectomy',
  'thrombocytopenic purpura', 'thromboembolism', 'thrombophlebitis', 'thrombus', 'thrush',
  'thymoma', 'thymus gland', 'thyroglossal cyst', 'thyroid gland', 'thyroiditis',
  'thyrotoxicosis', 'thyroxin', 'tia', 'tibia', 'tic douloureux', 'ticks',
  'tietze\'s syndrome', 'tinea', 'tinnitus', 'tipped uterus', 'tissue plasminogen activator',
  'tissue typing', 'tmj syndrome', 'tolerance', 'tonometry', 'tonsillectomy', 'tonsillitis',
  'tonsils', 'tourette\'s syndrome', 'tourniquet', 'toxemia', 'toxic epidermal necrolysis',
  'toxic shock syndrome', 'toxicity', 'toxin', 'toxocariasis', 'toxoplasmosis', 'tpa',
  'trachea', 'tracheitis', 'tracheotomy', 'trachoma', 'traction', 'transcutaneous',
  'transcutaneous electrical nerve stimulation', 'transferrin', 'transient ischemic attack',
  'transmissible', 'transplant', 'transurethral prostatectomy', 'travelers\' diarrhea',
  'tremor', 'triage', 'trichiasis', 'trichinosis', 'trichomoniasis', 'tricuspid valve',
  'tricyclic antidepressants', 'trigeminal neuralgia', 'triglyceride', 'trimester',
  'triple x syndrome', 'trismus', 'trisomy', 'trisomy 21', 'tubal ligation', 'tubal pregnancy',
  'tuberculin test', 'tuberous sclerosis', 'tuboplasty', 'tunnel vision', 'turner\'s syndrome',
  'tympanic membrane', 'tympanoplasty', 'typhoid fever', 'typhus', 'ulcer',
  'ulcerative colitis', 'ultrasound scanning', 'ultraviolet light', 'umbilical cord',
  'umbilical hernia', 'unconsciousness', 'undescended testicle', 'unsaturated fat', 'urea',
  'uremia', 'ureters', 'urethra', 'urethritis', 'urethrocele', 'urethrocystitis', 'urinalysis',
  'urinary diversion', 'urinary incontinence', 'urinary tract', 'urticaria',
  'uterine prolapse', 'uterus', 'uvea', 'uveitis', 'v/q lung scans', 'vaccination',
  'vacuum aspiration', 'vacuum extraction', 'vagina', 'vaginismus', 'vaginitis', 'valve',
  'valvotomy', 'valvuloplasty', 'varicella', 'varices', 'varicocele', 'varicose veins',
  'variola', 'vas deferens', 'vascular', 'vasculitis', 'vasectomy', 'vasoconstriction',
  'vasodilation', 'vasovagal attack', 'vein', 'venereal disease', 'venipuncture', 'venography',
  'venom', 'ventilation', 'ventilator', 'ventricle', 'ventricular fibrillation',
  'ventricular septal defect', 'vernix', 'version', 'vertebra', 'vertebral arteries',
  'vertebrobasilar insufficiency', 'vertex presentation', 'vertigo',
  'very low-density lipoprotein', 'vesicle', 'vestibular glands', 'villi', 'viral', 'viremia',
  'virilization', 'virulence', 'visual acuity', 'visual field', 'vital sign', 'vitamin a',
  'vitamin b complex', 'vitamin b12', 'vitamin b6', 'vitamin c', 'vitamin d', 'vitamin e',
  'vitamin k', 'vitamins', 'vitiligo', 'vitreous humor', 'vldl', 'vocal cords', 'volvulus',
  'von willebrand\'s disease', 'vulva', 'vulvitis', 'vulvovaginitis', 'walleye', 'wart',
  'weber\'s test', 'wegener\'s granulomatosis', 'weight-bearing exercise',
  'wernicke\'s encephalopathy', 'wheeze', 'whiplash injury', 'whipple\'s disease', 'whipworm',
  'white blood cell', 'white blood cell count', 'whitehead', 'whitlow', 'whooping cough',
  'wilm\'s tumor', 'wilson\'s disease', 'withdrawal bleeding', 'x chromosome',
  'x-linked disorder', 'x-ray', 'xanthelasma', 'xanthine', 'xanthomatosis',
  'xeroderma pigmentosum', 'xerophthalmia', 'xyy syndrome', 'y chromosome', 'yeast infection',
  'yellow fever', 'zift', 'zinc chloride', 'zollinger-ellison syndrome', 'zoonosis', 'zygote',
  'zygote intrafallopian transfer',
]

const escapeRegExp = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const sortedTerms = [...MEDICAL_TERMS].sort((a, b) => b.length - a.length)

export const MEDICAL_TERMS_REGEX = new RegExp(
  `\\b(${sortedTerms.map(escapeRegExp).join('|')})\\b`,
  'gi'
)

export const ambossSearchUrl = (term: string) =>
  `https://www.amboss.com/us/knowledge?q=${encodeURIComponent(term)}`
